### ISSUE TITLE
Crash in settings activity

### ISSUE THREAD

**Issue by nicolasbrailo** [nicolasbrailo/PianOli#43]
Received report by email:

[androidx.fragment.app](http://androidx.fragment.app/).Fragment$InstantiationException: Unable to
instantiate fragment
com.nicobrailo.pianoli.SettingsActivity$SettingsFragment: could not find
Fragment constructor
        ...
        at
com.nicobrailo.pianoli.SettingsActivity.onCreate(SettingsActivity.java:33)
        ...
Caused by: java.lang.NoSuchMethodException:
com.nicobrailo.pianoli.SettingsActivity$SettingsFragment.<init> []
        at java.lang.Class.getConstructor0(Class.java:2363)
        at java.lang.Class.getConstructor(Class.java:1759)
        at [androidx.fragment.app](http://androidx.fragment.app/).Fragment.instantiate(Fragment.java:613)

**Comment by nicolasbrailo** [comment]
Can't repro, but change should help.

**Comment by nicolasbrailo** [comment]
@pserwylo I got this crash report by email, and while I can't reproduce it, I tried a few changes that may help. If you think it's a bad idea, can you please let me know?
